### ISSUE TITLE
Site broken on IE

### ISSUE THREAD

**Issue by freyamade** [crnbrdrck/hello.world#6]
Awaiting screenshot from hero

**Comment by freyamade** [comment]
https://l.messenger.com/l.php?u=https%3A%2F%2Fwww.browserstack.com%2Fscreenshots%2Fe4e182b8f7dfca4e939f7126244e51612ee1d533%2Fwin7_ie_10.0.png&h=ATMzImWTjMgRa6jibmxSQ9WAJiysakaL9QJIOl2333GKjTz_Nd-Mv7QC_mf6gg2HP2AeA-swfc2_5OwAZK3Ap0uqD0P-WhsJsuFjMeB0JUGKESp6MMDD-oFq9hJj6H7P

https://l.messenger.com/l.php?u=https%3A%2F%2Fwww.browserstack.com%2Fscreenshots%2Fe4e182b8f7dfca4e939f7126244e51612ee1d533%2Fwin7_ie_8.0.png&h=ATMzImWTjMgRa6jibmxSQ9WAJiysakaL9QJIOl2333GKjTz_Nd-Mv7QC_mf6gg2HP2AeA-swfc2_5OwAZK3Ap0uqD0P-WhsJsuFjMeB0JUGKESp6MMDD-oFq9hJj6H7P

https://l.messenger.com/l.php?u=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Fmicrosoft-edge%2Ftools%2Fscreenshots%2F%3Furl%3Dhttp%253A%252F%252Fhello.exceptionalvoid.com%252Fcontrib%252F&h=ATMzImWTjMgRa6jibmxSQ9WAJiysakaL9QJIOl2333GKjTz_Nd-Mv7QC_mf6gg2HP2AeA-swfc2_5OwAZK3Ap0uqD0P-WhsJsuFjMeB0JUGKESp6MMDD-oFq9hJj6H7P

**Comment by hero24** [comment]
fixed
